name: CI

on:
  pull_request:
  push:
    branches:
      - main
  release:
    types: [published, prereleased]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint

  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm

      - name: Install
        run: npm ci

      - name: Test
        run: npm test

      - name: Build
        run: npm run bundle

      - name: Ensure dist is up to date
        run: git diff --exit-code

  publish:
    runs-on: ubuntu-latest
    needs: [lint, test-build]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/main') || github.event_name == 'release'
    permissions:
      contents: read
      id-token: write
      packages: write

    steps:
      - name: Checking out
        uses: actions/checkout@v6
      - name: Publish
        id: publish
        uses: actions/publish-immutable-action@0.0.4
